### ISSUE TITLE
discovery item detail page revisions

### ISSUE THREAD

**Issue by saverkamp** [NYPL/design-toolkit#108]
Here are my recommendations for improving metadata display in the item detail page. Some of these are data issues that cannot be immediately resolved, but including them here so we can plan for inclusion in the next beta.

**Missing from display (data available in API)**

- Alternative titles (`titleAlt`)
- Creator or "Author" (`creator`) -- I think @nonword is getting these into the index right now...
- Title display (`titleDisplay` ?) -- This is also getting into the index right now. This field was originally mapped to `title` from the entire 245 field, including the statement of responsibility (free text statement of author/creator/editor/etc.), BUT we realized this display made for more useful search results titles and decided to keep it as an additional field. So we revised `title` to include just the title and created `titleDisplay` for the whole statement. Up to you if you think it works for item page titles and/or search results titles. Here's an example: `Blah blah blah : stories of a theatre company, 1985-1995 / edited by Nicolas Whybrow.`
- Still need to do something with `mediaType` and `carrierType`

**Remove from display**

- Type
- Bnumber 
- OCLC Workid
- Issuance (I have an idea for how to display this and will follow up separately)

**Adjust display**
- Concatenate Place of Publication + Publisher. Makes more sense as one value if we're not stripping punctuation. Probably makes sense to use "Publisher" as label. 
- Concatenate Extent (currently missing from display) + Dimensions. Same reason as above. Maybe use "Physical description" for label?
- Date: Use only one date or date range. (We don't need both Date Created and Date Published--they are coming from the same data.) Here is one possible option for generating a display date: if `dateStartYear` == `dateEndYear`, use `dateStartYear`, else display "`dateStartYear` - `dateEndYear`" (if `dateEndYear` == 9999, replace `dateEndYear` value with "present")

**Missing data from datastore/API (my bad--we can include in the next beta)**
- LCCN
- ISBN
- ISSN

**Comment by mgiraldo** [comment]
I looked up [your example in the catalog](http://catalog.nypl.org/record=b13582339~S1): “Blah blah blah : stories of a theatre company, 1985-1995 / edited by Nicolas Whybrow.”

so Nicolas Whybrow is the author? this means we could assume that `titleDisplay` already includes it and not worry about that logic/piece of information?

**Comment by saverkamp** [comment]
`titleDisplay` should include it, but we still need to swap it out for `title` where appropriate. I believe that the search results title and the item page title are pulling the data from `title` right now. Up to you if you think it's better to use the full display title (with creator info) or just the title in each place.
