### ISSUE TITLE
should we use a css lint?

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/design-toolkit#14]
like [airbnb's](https://github.com/airbnb/css)?

**Comment by rhernand3z** [comment]
Yes, we should. I would include our HTML templates as well.
We need to ensure code quality around everything we implement from backend to frontend.

**Comment by mgiraldo** [comment]
any tips on getting the thing set up are welcome

**Comment by ricardoom** [comment]
If you have some kind of linter set up on your machine / editor you can put the .scss-lint.yml file in the root (i did this locally) and it should work...

**Comment by mgiraldo** [comment]
yeah but in a way that is compatible with whatever other pipeline process we use

**Comment by ricardoom** [comment]
so the idea is to have the linting done automagically via a build process.

**Comment by EdwinGuzman** [comment]
@mgiraldo What do you mean "with whatever other pipeline process"? Do you mean when you build the scss to css?

An editor that does linting on-the-fly like @ricardoom suggested is a good way of following the rules _while_ writing the scss. If you're building and exporting from scss to css, a pipeline process with grunt/gulp/webpack/etc shouldn't be too hard to find.

I think the biggest issue will not be linting the code after writing but documenting and letter other developers know what rules should be followed to write in the first place. The Airbnb's styleguide is something we should adopt too.

**Comment by mgiraldo** [comment]
using airbnb-based linter
