### ISSUE TITLE
Design for input type number

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/design-toolkit#141]
I think working in an `<input type="number" />` might be good for accessibility for the date fields. We can add limits and say we want a user to input numbers (dates in our case) between 1 to 9999 so that users don't try numbers that are more than 4 digits (9999, if I recall correctly, is a valid number in the Discovery API meaning it's an "on going" value).

If it's not `type="number"` we would have to add javascript to limit to just numbers but we can add `maxlength="4"`.

A problem with using `type="number"` is we'll see a form like so:

<img width="299" alt="screen shot 2017-05-18 at 9 15 37 pm" src="https://cloud.githubusercontent.com/assets/1280564/26229433/b5c7367c-3c0f-11e7-99a0-7b805da7b30b.png">

with the little arrows on the right side. I'll use maxlength for now and not use `type="number"` but I think it'll be worth looking into.

**Comment by mgiraldo** [comment]
agree
