### ISSUE TITLE
Tablet layout?

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/design-toolkit#15]
There are two breakpoints at 965 (mobile) and 1120 (intermediate). Will there be no tablet breakpoint? I know it's easier to just design for two layouts but tablet would be a "nice to have".

Check out the screenshots I took in this document:
https://docs.google.com/document/d/1v5vXdIX0KGRAYmyP4aiarqbnqWuL16hO0jANnjEIAbc/edit#heading=h.sxabc83uy0pb

It's a before/after of using the Design Toolkit grid system. The mobile and tablet views are pretty much the same. I also added screenshots of magnification at 200% for accessibility purposes and the view at that scale is functional.

@ricardoom @mgiraldo

**Comment by mgiraldo** [comment]
yeah we are thinking of adding an intermediate breakpoint (it's even there in the `_measurements.scss` file) but we first want to have the extremes figured out (desktop/phone)

**Comment by ricardoom** [comment]
I started using a middle width break point to accommodate the latest design pattern
