### ISSUE TITLE
Webpack 2.0

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/design-toolkit#172]
I can't seem to import the design-toolkit using Webpack 2.0's new syntax. Not sure if it's the lack of knowledge on my part of it this will need to be upgraded as well. Adding this as a placeholder.

For now, I'm reverting back to:
```
/*
Import style rules from NYPL Design Toolkit
*/
@import "~@nypl/design-toolkit/sass/nypl-normalize";
@import "~@nypl/design-toolkit/sass/toolkit";
```

CC @rhernand3z @mgiraldo @ricardogalvez

**Comment by ricardoom** [comment]
@EdwinGuzman is there some documentation about how `webpack 1.0` is doing it?

**Comment by EdwinGuzman** [comment]
[Yes there is!](https://github.com/NYPL/design-toolkit/blob/master/INSTALL.md)

**Comment by ricardoom** [comment]
@EdwinGuzman i know this one's been hanging out for a minute. Did it ever get sorted out?

**Comment by EdwinGuzman** [comment]
Yes, it did. CLOSE.
