### ISSUE TITLE
Omnisearch markup choices

### ISSUE THREAD

**Issue by seanredmond** [NYPL/design-toolkit#195]
The discovery "omnisearch" is marked up as a `fieldset`, but is not part of `form`. This is valid HTML, but:

1. Wherever used, it needs to be made to work without Javascript, for which it has to be a `form`
1. A `fieldset` requires a `legend`. We might opt for one with  a `form` but it would be compulsory here.

I recommend refactoring this a form as well as providing some guidance and how it might work without JS.

cc @wlla

**Comment by EdwinGuzman** [comment]
The omnisearch is a form in Discovery. We could help with the markup (but we forgot a legend in Discovery) and with making it work without JS.

**Comment by seanredmond** [comment]
Cool. We can to do some syncing between this and what has been implemented in Discovery, then.

**Comment by ricardoom** [comment]
syncing...

**Comment by ricardoom** [comment]
wait, @seanredmond is this something that needs to happen at the TK level? I see in the documentation, I need to wrap the omni-field in `<form>` but the rest of it is marked up as a fieldset. 

CC: @EdwinGuzman

**Comment by seanredmond** [comment]
I don't think it needs to be a fieldset, and if it is a fieldset it needs a legend (which we would then have to hide, etc etc). Maybe if it were one element among others in a form you'd make this part a fieldset, but that's not how we're using it.

**Comment by EdwinGuzman** [comment]
This is the DOM for the omnisearch that is currently on Dev for the discovery ui:

![screen shot 2017-08-16 at 5 05 09 pm](https://user-images.githubusercontent.com/1280564/29385300-258343f8-82a5-11e7-9403-b890aed7a23d.png)

**Comment by EdwinGuzman** [comment]
And, here's some scss overrides I had to make in order to get the button to have a better focusable state and not break the omnisearch:

```
// Override for the omnisearch div to work as a fieldset and
// allow focus on the search button.
div.nypl-omnisearch {
  height: 48px;

  &.nypl-spinner-field {
    overflow: inherit;
  }

  &.spinning {
    overflow: hidden;
  }
}
```
