### ISSUE TITLE
Remove debugging messages

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/design-toolkit#201]
We are starting to log messages in AWS Cloudwatch and the debug SASS messages show up there. It's not necessary there.

![screen shot 2017-08-15 at 11 29 29 am](https://user-images.githubusercontent.com/1280564/29322895-2c34b996-81ad-11e7-9584-767802ff89f1.png)

**Comment by ricardoom** [comment]
whats the tactic for clearing up these warnings?

**Comment by EdwinGuzman** [comment]
I think just removing the `@warn` from the scss files?

**Comment by ricardoom** [comment]
:thinking:

**Comment by ricardoom** [comment]
ok, for now I've commented out the `@warn` directives. You'll see the PR, let me know how the logs shake out afterwards.
