### ISSUE TITLE
Update [EDD Form] Example screen to reflect current Wireframe

### ISSUE THREAD

**Issue by ricardoom** [NYPL/design-toolkit#210]
See: https://app.moqups.com/digitalrepository@nypl.org/55BjtB7Pm0/edit/page/af6521aa2
for new layout & markup directives

**Comment by ricardoom** [comment]
@seanredmond / @EdwinGuzman if you guys have a minute here is the updated [EDD Form]

https://gist.github.com/ricardoom/9df951c86eb1b73a66819121e4ba030a

**Comment by EdwinGuzman** [comment]
It looks good to me.
