### ISSUE TITLE
Remaining capitalized texts

### ISSUE THREAD

**Issue by ktp242** [NYPL/design-toolkit#216]
There are still some texts and labels are capitalized. They have not been updated as they are from HTML content but not styles. I am not quite sure what is the final decision of the issue #192 . So I will list the remaining capitalized texts here, and please let me know if we need to normalize them. @willa @ricardoom @courtneymcgee @EdwinGuzman 

**Search Results**
- [ ] Request button in the Locations table

**Bib page**
- [ ] "Back to results" link
- [ ] All bibliographic fields
- [ ] Request buttons

**Request page**
- [ ] Submit request button

**EDD form page**
- [ ] Submit request button

**Comment by courtneymcgee** [comment]
Make these title case...

**Search Results**
- [ ] Request button: **Request**

**Bib Page**
- [ ] All bibliographic fields: **Title, Author, Additional Authors, Publication, Description, Subject, Genre/Form, Contents, ISSN, LCC**
- [ ] Fix **Additional Details** (capitalize the "D")
- [ ] Request button: **Request**

**Request Page**
- [ ] Fix **Submit Request** (capitalize the "R")

**EDD Form**
- [ ] Fix **Submit Request** (capitalize the "R")

**Comment by EdwinGuzman** [comment]
@ktp242 this should also go into the discovery-front-end app.

**Comment by ktp242** [comment]
ah darn! Can I move it now? If no, I can create a new one and move all the comments there

**Comment by ktp242** [comment]
Thanks @courtneymcgee!
