### ISSUE TITLE
finish up pa11y automated testing

### ISSUE THREAD

**Issue by ricardoom** [NYPL/design-toolkit#219]
Issue I'm having is configuring travis to run Jekyll and test the example URLs supplied by the `.pa11ic` 
The idea is (and it could be incorrect): Travis will install node, and install the TK and then run it, and then it will test the local URLs via the pa11y test... right now it makes it running the TK but it just runs the TK and never executes the npm test-pa11y command... I tried setting up a matrix in my travis.yml file but I cant seem to get the syntax right... any ideas are welcome!
thanks.
here's the releveant branch:
https://github.com/NYPL/design-toolkit/tree/add-pa11y

and the Travis page where you can run the current configuration... but you'll have to kill the build:
https://travis-ci.org/NYPL/design-toolkit

**Comment by seanredmond** [comment]
Maybe the `jekyll serve --detach` option is what you need? 

http://yizeng.me/2013/11/17/run-selenium-webdriver-ui-tests-against-jekyll-site-on-travis-ci/

**Comment by EdwinGuzman** [comment]
🔥
