### ISSUE TITLE
[Toolkit Updates]: Add generic modal to docs

### ISSUE THREAD

**Issue by ricardoom** [NYPL/design-toolkit#232]
Add a modal example to the docs

**Comment by ricardoom** [comment]
@seanredmond you can pull this branch, to see the in the docs: 

http://localhost:4000/design-toolkit/sections/microformats.html#modalsPopups

**Comment by ricardoom** [comment]
@seanredmond please take a look at this branch: 
https://github.com/NYPL/design-toolkit/tree/231-no-js
I could use help / advice on:

- Needs the inert.js (or some such polyfill) 
- Focusing the first element in the modal
- Escape key closing of modal
- Audit the completeness of documentation, before I send to @wlla for review

cc: @EdwinGuzman / @ktp242

**Comment by EdwinGuzman** [comment]
@ricardogalvez check out the PR https://github.com/NYPL/design-toolkit/pull/238
