### ISSUE TITLE
Filter checkboxes look weird in Safari

### ISSUE THREAD

**Issue by seanredmond** [NYPL/design-toolkit#233]
I don't think this is the intended look?

![screen shot 2017-10-03 at 11 11 37 am](https://user-images.githubusercontent.com/720703/31132796-b7a0e26c-a82b-11e7-9bd4-eeaea586245e.png)

**Comment by EdwinGuzman** [comment]
Is this in the Design toolkit or in Discovery?

**Comment by ricardoom** [comment]
@EdwinGuzman I'm assuming TK. 
I'm not seeing this error in my Safari. Investigating a vendor prefix for the `transform`
