### ISSUE TITLE
Pagination buttons and rel

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/design-toolkit#28]
In https://nypl.github.io/design-toolkit/tables.html the "previous" and "next" links should be buttons to be more accessible. Instead of `href="#prev"` a `rel` attribute should be added to note if the action will go to the next or previous page. That will also help index pages, more on that here: https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html.

**Comment by mgiraldo** [comment]
buttons are not necessarily more (or less) accessible. buttons are mostly used for website-affecting actions whereas links should be used for “moving around” (see [Nielsen](https://www.nngroup.com/articles/command-links/) and [others](http://uxmovement.com/buttons/when-to-use-a-button-or-link/)). even google's own bottom page navigation uses links

the `href="#prev"` was a placeholder for whatever proper previous or next link would be

i have [updated the docs](https://nypl.github.io/design-toolkit/tables.html#pagination) to reflect a “best practice” link and added the `rel` attributes

**Comment by mgiraldo** [comment]
my personal preference is to have the app behave _like_ a multipage app in spite of it being single page. 

eg: URL changes when next/prev is clicked, browser history increased by one entry, back button reverts to previous state, link can be copy/pasted in another browser to reproduce the state
