### ISSUE TITLE
Logic to check in the data for book, ebooks or both

### ISSUE THREAD

**Issue by ricardoom** [NYPL/design-toolkit#285]
We need some logic here that looks in the `json` file to determine if a pick has `catatlogUrl` or `ebookUrl` or both, and then render the proper block(s) of html... right now if, for example there is no ebookUrl in the `book` object the html is rendered, but where the url is, it returns undefined. Ideally it would not render the block of html at all. 

https://github.com/NYPL/design-toolkit/blob/431bd6b2c3e84188f545335ea6bf18569676d471/docs/js/contentCard.js#L19
 
Set up a condtional where we ask if the ebookUrl is present then render the right html block.

**Comment by ricardoom** [comment]
this commit should fix this issue:
https://github.com/NYPL/design-toolkit/commit/8725e9a32d325145e003e57c9908b7ab9300403e

@EdwinGuzman or @ktp242  could you take a look and let me know if this is the right approach? It works, but I'm curious how you would do it.

**Comment by ricardoom** [comment]
@EdwinGuzman thanks for taking a look. I'll keep at it.

**Comment by ricardoom** [comment]
@EdwinGuzman check the latest commit

**Comment by EdwinGuzman** [comment]
Yes.

A different minor change: `this.classesFromTags = (tag) => {` and `this.tagsRaw = (rawTag) => {` both take in an argument but it's not being used. When you call each function you also don't pass any arguments in. You're relying on the `pick` variable in the loop inside each function. It'd be better if those functions used only the variable passed to it:
```
this.tagsRaw = (pick) => {
   return pick.tags.map(rawTag => rawTag.replace(/\,/ , ', ');
}
```

and for those functions to be outside the loop, too.

**Comment by ricardoom** [comment]
@EdwinGuzman alright, fixed up the above issue(s)...

...next...

**Comment by ricardoom** [comment]
closing
