### ISSUE TITLE
Can't import using webpack

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/design-toolkit#32]
I tried to import the `design-toolkit` with the steps in the readme but failed at step 2 - loading the sass through the webpack config. I'm also not sure if the step 3 is correct - import through `@import "toolkit";` because of the name (it could have been written before the "design-toolkit" name was finalized).

This is one example of an error I encountered:
![screen shot 2017-01-11 at 3 30 07 pm](https://cloud.githubusercontent.com/assets/1280564/21867628/061164ce-d81d-11e6-879d-856453273b36.png)

Importing without the tilde provided the same error.

I am currently importing files individually and will wait until Rafael gets back to work with him on this issue. Working example:

```
@import "~@nypl/design-toolkit/sass/grid";
```

**Comment by EdwinGuzman** [comment]
Also worth noting that I did see issues when importing using webpack that I could not load it because it couldn't find "..img/svg...". So there's an svg file dependency in the toolkit and webpack cannot pick up those relative file directories. Might be worth investigating if that's the real issue.

**Comment by mgiraldo** [comment]
that "..img" looks suspicious... a possible missing slash somewhere?

**Comment by mgiraldo** [comment]
still problems with this, @EdwinGuzman ?

**Comment by EdwinGuzman** [comment]
I'll give it another shot soon.

**Comment by EdwinGuzman** [comment]
I tried it again and still can't load it simply by doing `@import "~@nypl/design-toolkit";`. I don't see any errors regaring the `..img` path.

**Comment by mgiraldo** [comment]
😔

i guess we have to wait for rafael to return to see how to fix that

**Comment by rhernand3z** [comment]
Issue fixed in version v0.1.3

commit -- https://github.com/NYPL/design-toolkit/commit/1d31970c625353fc4ce631283496db207593a1a3
