### ISSUE TITLE
Add support for input type number and email on 'nypl-text-field' class

### ISSUE THREAD

**Issue by rhernand3z** [NYPL/design-toolkit#47]
Right now, the 'nypl-text-field' class looks specifically for input[type='text'] to add styling, other types should be supported such as email and number.

**Comment by mgiraldo** [comment]
fixed in 7d2db3d6ec5d56774ffc2ce14b2a24519bb9b5a8

**Comment by mgiraldo** [comment]
(not in npm yet)
