### ISSUE TITLE
Add utility classes for form input field erros

### ISSUE THREAD

**Issue by rhernand3z** [NYPL/design-toolkit#49]
When using client-side JS validation, an html element, typically a div or span is inserted to the DOM to provide a visual cue to the user that the current field being entered is not a valid format. We need to add a helper class like 'nypl-required-field' to add styling to such fields.

CC: @ricardoom

**Comment by mgiraldo** [comment]
solved in af3451d793af1c46388fe96e574d7e0025417378 and [documented here](https://nypl.github.io/design-toolkit/sections/forms.html#fieldErrors)
