### ISSUE TITLE
Remove strict global rules on html elements

### ISSUE THREAD

**Issue by rhernand3z** [NYPL/design-toolkit#54]
The toolkit is enforcing strict styling rules to <a>, <footer>, <ul> and others to include pseudo selectors (i.e. :focus, :active, :link).

If the intention is for this to co-exist with other applications, global rules should be avoided. At the moment, global rules affect the NYPL Footer for the Get a Library Card App.
@mgiraldo @ricardoom 

Would be ideal to address before GALC launch.

**Comment by mgiraldo** [comment]
some styling/html issues happened and the issue is not completely readable on github 🤔
