### ISSUE TITLE
Facet count number float past right border

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/design-toolkit#59]
Depending on the length of the name of the facet and the count length, the count number floats past the right border.

<img width="309" alt="screen shot 2017-04-20 at 11 53 49 pm" src="https://cloud.githubusercontent.com/assets/1280564/25262258/da6cedba-2624-11e7-8916-7c461b930e02.png">

**Comment by mgiraldo** [comment]
i will need to change the html structure of the widget to accommodate arbitrary-sized numbers. will keep you posted. or we could also truncate the numbers (like 1.3M instead of the longer version... unless the precision is very important for users)

**Comment by EdwinGuzman** [comment]
You're not making pull requests for these issues/changes?

**Comment by mgiraldo** [comment]
pushing directly to master like a boss 💪

i guess it is a good idea that i do it in a more proper way 👀
