### ISSUE TITLE
Initial state of the Pagination

### ISSUE THREAD

**Issue by EdwinGuzman** [NYPL/design-toolkit#61]
I'm currently displaying the "Previous" button only when it's not the first page. In that case, the text floats from the center to the left. I think not displaying the button is better than displaying it but displaying it. What do you think?

<img width="924" alt="screen shot 2017-04-21 at 12 01 15 am" src="https://cloud.githubusercontent.com/assets/1280564/25262404/d2267b34-2625-11e7-9968-2873c9bd10d4.png">

**Comment by mgiraldo** [comment]
a small fix is coming… i agree not showing it is better
