### ISSUE TITLE
$bordercolor variable

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/design-toolkit#7]
<a href="https://github.com/beefoo"><img src="https://avatars.githubusercontent.com/u/67169?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [beefoo](https://github.com/beefoo)**
_Fri Dec 16 20:21:41 2016_
_Originally opened as https://github.com/NYPL/design/issues/7_

----

in _colors.scss ... something like:

```
$bordercolor: $nypllightgray;
```

**Comment by mgiraldo** [comment]
<a href="https://github.com/mgiraldo"><img src="https://avatars.githubusercontent.com/u/133020?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mgiraldo](https://github.com/mgiraldo)**
_Mon Dec 19 20:01:09 2016_

----

is this a general border? like a separator of two divs? if this is the case, use `$pagetextcolor`.

**Comment by beefoo** [comment]
Yeah, a few examples:

As a separator of search results:
http://dev-discovery.nypl.org/search?q=war

And separator of rows and sections:
http://dev-discovery.nypl.org/item/b11183568

**Comment by mgiraldo** [comment]
i'd say use `$page-text-color` then. 

i will be working on the discovery search results page now. in the meantime you could try applying `basic-table` to the holdings table and see how it looks and what else is needed?
