### ISSUE TITLE
add the toolkit design statement

### ISSUE THREAD

**Issue by wlla** [NYPL/design-toolkit#82]
Include best practice of using percent, em, or named font size rather than px somewhere in toolkit.

**Comment by mgiraldo** [comment]
it should better be a “general statement” about the toolkit? because if things are followed, one shouldn't be typing CSS at all...

**Comment by mgiraldo** [comment]
added [`docs/_sections/about.md`](https://github.com/NYPL/design-toolkit/blob/master/docs/_sections/about.md) to address this

**Comment by wlla** [comment]
also include information on styling of links

**Comment by mgiraldo** [comment]
see “no CSS” above. people will just make an `<a href="yada">link</a>` and the style itself will be inherited from the toolkit... the idea is to save people from worrying about it

**Comment by mgiraldo** [comment]
updated the issue to better reflect the purpose

**Comment by mgiraldo** [comment]
addressed in #90
