### ISSUE TITLE
[Toolkit]: Fix the logo rendering on the SVG toolkit page

### ISSUE THREAD

**Issue by ricardoom** [NYPL/design-toolkit#86]
on the [SVG toolkit page](https://nypl.github.io/design-toolkit/sections/svg-index.html), the logo is microscopic. fix it.

**Comment by mgiraldo** [comment]
that page needs a general revision... i remember we had a workaround for this which was defaulting the `nypl-icon` mixin to 10x10rem but that proved problematic in other parts of the code that used it... so i defaulted to 1x1rem, thus “breaking” this particular example... the nypl logo should have a special mixin and not rely on the generic `nypl-icon` abstraction which is supposed to be used for “normal” icons that might be used throughout a page

**Comment by ricardoom** [comment]
My sentiments exactly.  Will come up w/ a solution

**Comment by ricardoom** [comment]
addressed by #242

**Comment by ricardoom** [comment]
closed via #242
