### ISSUE TITLE
Status colors

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/design-toolkit#9]
<a href="https://github.com/beefoo"><img src="https://avatars.githubusercontent.com/u/67169?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [beefoo](https://github.com/beefoo)**
_Fri Dec 16 20:29:20 2016_
_Originally opened as https://github.com/NYPL/design/issues/9_

----

I'm not exactly sure how to generalize this, but for our use-case, we're using colors to reinforce the availability status of an item and the ready-status of a hold request (e.g. green = available or ready).  Note that there can also be a recommendation to "not use colors to indicate/reinforce meaning"

**Comment by mgiraldo** [comment]
<a href="https://github.com/mgiraldo"><img src="https://avatars.githubusercontent.com/u/133020?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mgiraldo](https://github.com/mgiraldo)**
_Mon Dec 19 20:15:21 2016_

----

do you have an example link for this?

in general we are avoiding relying on color in favor of text (eg: “available”, “not available”). availability can also be reinforced with the presence or absence of buttons.

as we design the request/hold process we can decide if color is required.

**Comment by beefoo** [comment]
Here's one example for availability status of a patron's holds:
https://nypl-discovery.github.io/discovery-designs/holds/v1a.html

And another example for availability status in a search result:
http://dev-discovery.nypl.org/search?q=war

To your point, it makes sense that the "request hold" button should be absent if it is not available.  So in the "War" example, should we remove the green/orange colors?

**Comment by mgiraldo** [comment]
first pass at this in 894638cc77189c1cd1c2ac45bc1c1a5f0ecb718f
