### ISSUE TITLE
add aria-labelledby to required fields

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/design-toolkit#94]

**Comment by wlla** [comment]
Related: investigate and resolve validation hiccup. Currently, _tabbing_ focus into a required field prompts screen readers to read out "invalid entry" before user has made any input. Investigate and resolve.

**Comment by mgiraldo** [comment]
yeah the JS validation example is not exhaustive. simplified it a bit to happen on change (eg: type something press ENTER)
